version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: kids_spelling_mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: kids_spelling_game
      MYSQL_USER: spelling_user
      MYSQL_PASSWORD: spelling_password
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    command: --default-authentication-plugin=mysql_native_password
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      timeout: 20s
      retries: 10

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: kids_spelling_phpmyadmin
    restart: always
    ports:
      - "8080:80"
    environment:
      PMA_HOST: mysql
      PMA_USER: root
      PMA_PASSWORD: rootpassword
    depends_on:
      mysql:
        condition: service_healthy

  backend:
    build: ./backend
    container_name: kids_spelling_backend
    restart: always
    ports:
      - "3000:3000"
    environment:
      - DB_HOST=mysql
      - DB_USER=spelling_user
      - DB_PASSWORD=spelling_password
      - DB_NAME=kids_spelling_game
    depends_on:
      mysql:
        condition: service_healthy
    volumes:
      - ./backend:/app
      - /app/node_modules

  frontend:
    build: ./kids-spelling-game
    container_name: kids_spelling_frontend
    restart: always
    ports:
      - "4200:4200"
    depends_on:
      - backend
    volumes:
      - ./kids-spelling-game:/app
      - /app/node_modules

volumes:
  mysql_data: 